
import numpy as np
from numba import jit
from multiprocessing import Pool
from functools import partial
import os

from .utils import get_pos_dec

@jit(nopython=True)
def _hist_rS_sta(r, S, bins):
    n_bins = len(bins)
    hist_r = np.zeros(len(bins)-1)
    hist_S = np.zeros(len(bins)-1)
    for i in range(len(r)):
        for j in range(n_bins):
            if r[i]<bins[j]:
                break
        hist_r[j-1]+=1
        hist_S[j-1]+=S[i]
    return hist_r, hist_S

@jit(nopython=True)
def _hist_rS_dyn(r, S, bins):
    n_bins = len(bins)
    n_dt = len(S)
    hist_r = np.zeros(n_bins-1)
    hist_S = np.zeros((n_dt, n_bins-1))
    for i in range(len(r)):
        for j in range(n_bins):
            if r[i]<bins[j]:
                break
        hist_r[j-1]+=1
        for k in range(n_dt):
            hist_S[k,j-1]+=S[k,i]
    return hist_r, hist_S

def _update_npz_savefile(path):
    print(path)
    files = os.listdir(path)
    print(len(files), ' files')
    Li0, Ln, LS = [], [], []
    for i, file in enumerate(files):
        with open(rf'{path}{file}') as f: #get header
            first_line = f.readline()
            header = first_line[1:].strip() if first_line.startswith("#") else None

        if header is None: #static case
            r, dr, n, S = np.loadtxt(rf'{path}{file}').T
            i0 = int(file.replace('.txt', ''))
            Li0.append(i0)
            Ln.append(n)
            LS.append(S)
        else:
            if i != 0 and header != prev_header: #check for inconsistencies
                raise RuntimeError
            r, n, *S = np.loadtxt(rf'{path}{file}').T
            i0 = int(file.replace('.txt', ''))
            Li0.append(i0)
            Ln.append(n)
            LS.append(S)
        prev_header = header

    if header is None:
        np.savez(rf'{path[:-1]}.npz', r, dr, Li0, Ln, LS)
    else:
        dt = [float(x) for x in header.split(",")[2:-1]]
        np.savez(rf'{path[:-1]}.npz', r, dt, Li0, Ln, LS)

def _process_static_cross_correlations(i0, dips, pos, cell, bins, Ndips, savefolder): 
    # compute the static cross correlations for a timeframe i0
    dips_ = dips[i0,:,:]
    pos_ = pos[i0,:,:]
    cell_ = cell[i0,:]

    hist_r = np.zeros(len(bins)-1)
    hist_S = np.zeros(len(bins)-1)

    for j in range(Ndips):
        pos_dec = get_pos_dec(pos_, cell_, j)
        r = np.linalg.norm(pos_dec[:j+1,:] - pos_dec[j,:][np.newaxis,:], axis=-1)
        S = np.sum(dips_[:j+1,:] * dips_[j,:][np.newaxis,:], axis=-1)
        hist_r_, hist_S_ = _hist_rS_sta(r, S, bins)
        hist_r+=hist_r_
        hist_S+=hist_S_
    np.savetxt(f'{savefolder}{i0}.txt', np.array([bins[1:], np.diff(bins), hist_r, hist_S]).T)


def static_cross_correlations(fname, Li0_step, bins, savefolder, N_threads=1, recompute=False):
    """
    Computes static cross correlations using the virtual cavity method

    Parameters
    ----------
    fname : str
        name of the .npz file containing the dipole vectors and positions
    Li0_step : list
        list of t index for which the static cross correlation will be computed
    bins : np.array
        bins for the radius
    savefolder: str
        path to the save folder
    N_threads: int
        number of threads over which the computation will be parallelized
    recompute: bool
        if False, skip i0 values for which a .txt file is already present in the save folder

    Example
    -------
    >>> bins = np.concatenate((np.arange(0, 25, 0.5), np.arange(25, 55, 1.0)))
    >>> dielcav.static_cross_correlations(f'./out/dipoles_320K_1', Li0_step=5, bins=bins, savefolder=f'./out/static_cross_corr_320K_1/', N_threads=1, recompute=False)
    """

    with np.load(f'{fname}.npz') as data:
        t = data['t']
        dips = data['dipoles']
        pos = data['dipoles_pos']
        cell = data['cell']

    imax, Nmol, Ndip_mol = dips.shape[:3]
    Ndips = Nmol*Ndip_mol
    dips = dips.reshape(len(dips), Ndips, 3)
    pos = pos.reshape(len(pos), Ndips, 3)

    Li0 = range(0, imax, Li0_step)

    if not os.path.exists(savefolder):
        # if the save folder does not exist, it is created
        os.makedirs(savefolder)
        print('folder created')
    else:
        # if it already exists, we look at the i0 values that were computed already
        files = os.listdir(savefolder)
        if not recompute:
            Li0_done = [int(f.replace('.txt', '')) for f in files]
            Li0 = list(set(Li0)-set(Li0_done))
            print(Li0_done, ' already done')
            print(Li0, ' todo')

    process = partial(_process_static_cross_correlations, 
        dips=dips, pos=pos, cell=cell, bins=bins, Ndips=Ndips, savefolder=savefolder)
    

    if N_threads == 1:
        # no paralellization
        for i0 in Li0:
            process(i0)
    else:
        pool = Pool(N_threads)
        pool.map(process, Li0)

    _update_npz_savefile(savefolder)

def compute_static_gk_r(fname):
    """
    Extract gk(r) from the .npz file generated by the static_cross_correlations function
    
    Parameters
    ----------
    fname : str
        name of the .npz file

    Returns
    -------
    r: np.array
        cavity size
    gkr: np.array
        r-dependent Kirkwood correlation function. 
    gkr_std: np.array
        standard deviation of gkr
    gr: np.array
        pair correlation function of the center of charges.
    Phi: np.array
        fraction of molecules of the simulation box within the cavity of radius r.

    Example
    -------
    >>> r, gkr, gkr_std, gr, Phi = dielcav.compute_static_gk_r(f'./out/static_cross_corr_320K_1')
    """

    with np.load(f'{fname}.npz') as data:
        r = data['arr_0']
        dr = data['arr_1']
        Li0 = data['arr_2']
        Ln = data['arr_3']
        LS = data['arr_4']

    LS[:,1:]*=2 #because we did sum_i sum_j<=i
    Ln[:,1:]*=2 
    gk = np.cumsum(LS, axis = 1)/LS[:,0][:,np.newaxis]

    return r, np.mean(gk, axis=0), np.std(gk, axis=0), np.mean(Ln, axis=0)/dr/Ln[0,0]/(r-dr/2)**2, np.cumsum(np.mean(Ln, axis=0))/Ln[0,0]

def _process_dynamic_cross_correlations(i0, dit_val, t, dips, pos, cell, bins, Ndips, savefolder):
        # compute cross correlations starting from a timeframe i0
        dit = i0 + dit_val
        t_ = t[dit] - t[i0]
        dips_ = dips[dit,:,:]
        pos_ = pos[dit,:,:]
        cell_ = cell[dit,:]

        hist_d = np.zeros(len(bins)-1)
        hist_S = np.zeros((len(dit), len(bins)-1))

        for j in range(Ndips):
            pos_dec = get_pos_dec(pos_, cell_, j)
            d = np.linalg.norm(pos_dec[0,:j+1,:] - pos_dec[0,j,:][np.newaxis,:], axis=-1) # attention on prend la position à t = 0 (dim = (Nd))
            S = np.sum(dips_[0,j,:][np.newaxis,np.newaxis,:] * dips_[:,:j+1,:], axis=-1) # (dim = (Nd*Nt))
            hist_d_, hist_S_ = _hist_rS_dyn(d, S, bins)
            hist_d+=hist_d_
            hist_S+=hist_S_

        header = 'r, d, ' + ''.join([f'{_:.2f},' for _ in t_])
        np.savetxt(f'{savefolder}{i0}.txt', np.vstack((bins[1:], hist_d, hist_S)).T, header=header)

def dynamic_cross_correlations(fname, Li0_step, dit_val, bins, savefolder, N_threads=1, recompute=False):
    """
    computes dynamics cross correlations using the virtual cavity method

    Parameters
    ----------
    fname : str
        name of the .npz file containing the dipole vectors and positions
    Li0_step : list
        list of t index for which cross correlations will be computed
    dit_val : np.array
        list of dt values
    bins : np.array
        bins for the radius
    savefolder: str
        path to the save folder
    N_threads: int
        number of threads over which the computation will be parallelized
    recompute: bool
        if False, skip i0 values for which a .txt file is already present in the save folder

    Example
    -------
    >>> bins = np.concatenate((np.arange(0, 25, 0.5), np.arange(25, 55, 1.0)))
    >>> dit_val = np.array([0,1,2,4,8,16,32,64,128,256])
    >>> dielcav.dynamic_cross_correlations(f'./out/dipoles_320K_1', Li0_step=50, dit_val=dit_val, bins=bins, savefolder=f'./out/dyn_cross_corr_320K_1/', N_threads=1, recompute=False)
    """

    with np.load(f'{fname}.npz') as data:
        t = data['t']
        dips = data['dipoles']
        pos = data['dipoles_pos']
        cell = data['cell']

    imax, Nmol, Ndip_mol = dips.shape[:3]
    Ndips = Nmol*Ndip_mol
    dips = dips.reshape(len(dips), Ndips, 3)
    pos = pos.reshape(len(pos), Ndips, 3)

    Li0 = range(0, imax - max(dit_val) -1, Li0_step)

    if not os.path.exists(savefolder):
        # if the save folder does not exist, it is created
        os.makedirs(savefolder)
        print('folder created')
    else:
        # if it already exists, we look at the i0 values that were computed already
        files = os.listdir(savefolder)
        if not recompute:
            Li0_done = [int(f.replace('.txt', '')) for f in files]
            Li0 = list(set(Li0)-set(Li0_done))
            print(Li0_done, ' already done')
            print(Li0, ' todo')

    process = partial(_process_dynamic_cross_correlations, 
        dit_val=dit_val, t=t, dips=dips, pos=pos, cell=cell, bins=bins, Ndips=Ndips, savefolder=savefolder)

    if N_threads == 1:
        # no paralellization
        for i0 in Li0:
            process(i0)
    else:
        pool = Pool(N_threads)
        pool.map(process, Li0)

    _update_npz_savefile(savefolder)

def compute_dynamic_gk_r(fname):
    """
    Extract gk(r,t) from the .npz file generated by the dynamic_cross_correlations function
    
    Parameters
    ----------
    fname : str
        name of the .npz file

    Returns
    -------
    r: np.array
        cavity size
    t: np.array
        time
    gkr: np.array
        gkr(r, t) is the r and t dependent Kirkwood correlation function. 

    Example
    -------
    >>> r, t, gkrt = dielcav.compute_dynamic_gk_r('out/dyn_cross_corr_320K_1')
    """
    
    with np.load(f'{fname}.npz') as data:
        r = data['arr_0']
        dt = data['arr_1']
        Li0 = data['arr_2']
        Ln = data['arr_3']
        LS = data['arr_4']
    LS[:,:,1:]*=2 #because we did sum_i sum_j<=i
    Ln[:,1:]*=2 

    return r, dt, np.cumsum(np.mean(LS, axis=0)[:,:], axis=1)/LS[0,0,0]

